<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="0.725">
  <testcase classname="__main__.qa_RPi_Rx" name="test_001_t" time="0.7244">
    <failure type="exceptions.AssertionError">1 != 0.0 within 6 places
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/user/gnuradio/gr-custom/python/qa_RPi_Rx.py", line 44, in test_001_t
    self.assertFloatTuplesAlmostEqual(expected_result, result_data, 6)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 90, in assertFloatTuplesAlmostEqual
    self.assertAlmostEqual (a[i], b[i], places, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 559, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
